
functional:
  - Соревнование двух игроков в решении задач
  - Просмотр кода оппонента в реальном времени
  - Система рейтингов
  - Игра с ботом
  - Игра с другом по ссылке
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
